-- Create the table to store each rail segment
CREATE TABLE rail_lines (
  -- A unique ID for each line segment
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  
  -- The original properties (maxspeed, service, etc.)
  properties JSONB,
  
  -- The PostGIS geometry column
  -- 4326 is the standard GPS coordinate system (WGS 84)
  geom GEOMETRY(LineString, 4326),
  
  -- These columns will be added by pgRouting
  source BIGINT,
  target BIGINT
);

-- Create a spatial index for SUPER fast geometry queries
-- This is ESSENTIAL for performance
CREATE INDEX rail_lines_geom_idx
ON rail_lines
USING GIST (geom);